### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Kneudel** [aperezm85/streamdeck-tado-plugin#10]
Don't install and use the plugin. It doesn't work anymore an isn't updated for 2 years.

**Comment by aperezm85** [comment]
Hello Kneudel,
I have the plugin installed without issues in 2 stream deck.

Could you share more information on why it doesn’t work? I will take a look
this weekend and get back to you.

Regards,

**Comment by Kneudel** [comment]
Hi Aperes,

yes of course.

1. Most labes are "undefined" or not set
2. Icons don't display anything. Neither the "on/off" nor the "current temperature".

<img width="565" alt="Bildschirmfoto 2024-04-25 um 09 17 54" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/9333d8b4-1353-41f7-970f-b08bb2aa9592">
<img width="600" alt="Bildschirmfoto 2024-04-25 um 09 18 03" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/7ff9684c-51d5-4cc6-b6e9-32380e31e98b">
<img width="648" alt="Bildschirmfoto 2024-04-25 um 09 19 23" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/2c758784-5ec6-4e9d-b778-1bbbb7a90229">
<img width="192" alt="Bildschirmfoto 2024-04-25 um 09 19 58" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/c15ddce0-3e2e-4fa1-ac42-c4379bfeddd0">
<img width="579" alt="Bildschirmfoto 2024-04-25 um 09 20 03" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/b95bb7ed-4054-42a3-bb72-d9c736e710bb">
<img width="632" alt="Bildschirmfoto 2024-04-25 um 09 20 09" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/cb29224f-949b-4086-bd0c-586dbaef2be2">

**Comment by aperezm85** [comment]
Thanks for sharing
That looks like is an error on the translations file.
Could you confirm your language on the stream deck?
Currently the plugin only supports Spanish, German and English.
I think by default it should show the English one, but seems like it failed.

**Comment by Kneudel** [comment]
Hi, it's German.

**Comment by aperezm85** [comment]
Ok thanks, I will try to take a look over the weekend (I am away right now)
and I will try to deploy a fix. I’ll keep you informed.

**Comment by Kneudel** [comment]
Great. Thank you.

**Comment by aperezm85** [comment]
Hello @Kneudel.

I just updated the plugin with the german translation. You can find it on the releases [here](https://github.com/aperezm85/streamdeck-tado-plugin/releases/tag/2.1)

I didn't submitted it yet because I need to provide some images for the marketplace.
I used Google translator to generate the translations, so feel free to let me know if they are incorrect and I could change them [translations file](https://github.com/aperezm85/streamdeck-tado-plugin/blob/2.1/Sources/dev.aperez.tado.sdPlugin/de.json)

Thanks for your feedback.
Hope this fix your issues, if not, please let me know and I will take a look again.

Regards,
Alex

**Comment by Kneudel** [comment]
@aperezm85 thank you. I will install and test it and give you an update...

**Comment by Kneudel** [comment]
@aperezm85 translations looks well and the plugin work. 

One label isn't still fully translated. It's on the configuration panel of the "On/Off" Widget.
<img width="249" alt="Bildschirmfoto 2024-04-27 um 21 04 02" src="https://github.com/aperezm85/streamdeck-tado-plugin/assets/86220481/96b55a30-d153-4e66-9431-157dab2903b2">

And one Bug still exists. If there is no configuration and one add a new configuration, the widget config doesn't changed. Only after adding on the two widget to a key shows the added configuration.

**Comment by howies** [comment]
Login works, but I always get 'No Rooms'  in the room selector.

**Comment by aperezm85** [comment]
Hello @howies 
Could you try to turn off and on your stream deck?
I notice lately that happens on mine too.
Also, which streamdeck do you have?
thanks!

**Comment by howies** [comment]
Hi, I just use the streamdeck mobile app, not the physical device yet.  I justed wanted to test out several plugins before I buy the physical product.  thx

**Comment by aperezm85** [comment]
Thanks for your answer @howies 

I never used the mobile one, but I will add it to the list of improvements!

**Comment by theletterf** [comment]
Same issue with No rooms here.

**Comment by aperezm85** [comment]
Could you add more information please?
Which stream deck are you using? Which Operating system are you using?

Thanks

**Comment by theletterf** [comment]
Sure.

- Elgato Stream Deck Mini
- Stream Deck version 6.8.1 (21263) in Spanish
- My tado account has only one room

Logs:

```
17:36:07.132 Start polling to create cache
17:36:08.973 Localizations is not a valid json.
17:50:32.641 Stop polling to create cache
17:53:06.830 Start polling to create cache
17:53:12.648 Stop polling to create cache
17:53:14.335 Start polling to create cache
17:53:14.395 Localizations is not a valid json.
17:53:48.691 Localizations is not a valid json.
17:55:42.731 Localizations is not a valid json.
17:55:46.819 Localizations is not a valid json.
17:55:47.294 Could not connect to tado.
17:55:55.999 Could not connect to tado.
17:56:04.276 No room configured
17:56:18.768 No room configured
17:56:27.214 No room configured
17:56:28.533 No room configured
17:59:38.438 Localizations is not a valid json.
```

**Comment by aperezm85** [comment]
Seems like the language for the location is not supported (weird because I
have the Spanish translation file).
I am trying to set my language to spanish to test, but Stream Deck is not
doing it easy

**Comment by theletterf** [comment]
I set the language to English, still no luck.

**Comment by Kneudel** [comment]
do you use Tado V3 or Tado X?

**Comment by aperezm85** [comment]
It's using the Tado V2 API (that I think works for V3). I don't have any
Tado X device at home, and Tado did not offer any public API for it.

**Comment by theletterf** [comment]
I'm using Tado X devices.

**Comment by Kneudel** [comment]
Mmh. It doesn‘t support Tado X

**Comment by MiniFido** [comment]
Tado updatet the API so it will not work if the user dont updatet it. and dont look like it.. 
@aperezm85

**Comment by aperezm85** [comment]
Yes, they sent an email last week giving the notice that the API auth method will change.
I am currently working on a new version using the new auth method and the new Elgato SDK. 
The app has not being approved yet on the marketplace, but you can download and test the current development version from here:
https://github.com/aperezm85/streamdeck-tado-v2-plugin 

It has some issues (working on them) and I am adding support to the stream deck +.
I hope this one works for you.

Regards
